### ISSUE TITLE
SClang-vars.el Needs Edit

### ISSUE THREAD

**Issue by KonVas** [supercollider/scel#36] opened 2020-12-21 08:19 UTC
Hello, I am mirroring (not cloned as a local folder) `scel` in my Emacs/doom editor like this: 
`(package! sclang-mode
  :recipe (:host github :repo "supercollider/scel" :files ("el/*.el")))`

Apparently the [sclang-vars.el.in](https://github.com/supercollider/scel/blob/master/el/sclang-vars.el.in) in the `el` folder is expected as `sclang-vars.el` I am not sure if I should make a change my self, so I am opening this as an issue instead. Below is the aforementioned message: 
`Warning (initialization): An error occurred while loading ‘/Users/konstantinos/.emacs.d/init.el’:

Error in private config: config.el, (file-missing Cannot open load file No such file or directory sclang-vars)

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace`

**Comment by brianlheim** [comment] 2020-12-25 17:11
duplicate of #22

**Closed by brianlheim** 2020-12-25 17:11 UTC
