### ISSUE TITLE
SC_EL not building properly on ubuntu 18.04

### ISSUE THREAD

**Issue by wtkns** [supercollider/scel#24] opened 2020-03-29 02:14 UTC
## Environment

* SuperCollider version: Source Branch: develop
* Operating system: Ubuntu 18.04
* Other details (Qt version, audio driver, etc.): Emacs and suggested packages were installed with apt, emacs loads, but hasn't been thoroughly tested.

```
emacs/bionic,bionic,now 47.0 all [installed]
emacs25/bionic,now 25.2+1-6 amd64 [installed,automatic]
emacs25-bin-common/bionic,now 25.2+1-6 amd64 [installed,automatic]
emacs25-common/bionic,bionic,now 25.2+1-6 all [installed,automatic]
emacs25-common-non-dfsg/bionic,bionic,now 25.2+1-1 all [installed,automatic]
emacs25-el/bionic,bionic,now 25.2+1-6 all [installed,automatic]
emacsen-common/bionic,bionic,now 2.0.8 all [installed,automatic]
```

## Steps to reproduce

When running make on develop branch on Ubuntu 18.04 with CMAKE flags:
  
`CMAKE_BUILD_TYPE=Release NATIVE=ON SC_EL=ON`

## Expected vs. actual behavior
**make crashes as follows:**

```
[ 93%] Built target SuperCollider
[ 93%] Built target sclang.elc
[ 93%] Built target sclang-interp.elc
[ 93%] Built target sclang-language.elc
[ 93%] Built target sclang-document.elc
[ 94%] Built target sclang-keys.elc
[ 94%] Creating byte-compiled Emacs lisp /home/jms/git/SuperCollider/build/editors/sc-el/el/sclang-help.elc
Loading 00debian-vars...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50cmake-data.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...

In toplevel form:
sclang-help.el:86:7:Warning: assignment to free variable ‘w3m-use-filter’
sclang-help.el:89:18:Warning: reference to free variable ‘w3m-filter-rules’
sclang-help.el:89:18:Warning: assignment to free variable ‘w3m-filter-rules’
sclang-help.el:261:1:Error: Symbol’s function definition is void: gensym
editors/sc-el/el/CMakeFiles/sclang-help.elc.dir/build.make:60: recipe for target 'editors/sc-el/el/sclang-help.elc' failed
make[2]: *** [editors/sc-el/el/sclang-help.elc] Error 1
CMakeFiles/Makefile2:4335: recipe for target 'editors/sc-el/el/CMakeFiles/sclang-help.elc.dir/all' failed
make[1]: *** [editors/sc-el/el/CMakeFiles/sclang-help.elc.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```

Works fine for me if i set SC_EL=OFF. I don't need a fix, but wanted to let you know, since SC_EL=ON is the default.

**Comment by brianlheim** [comment] 2020-03-29 02:34
@wtkns thanks for the report. i transferred your issue here since scel is a separate repo. what hash of the scel submodule did you experience this with? can you try with the latest master (of scel, not supercollider)?

**Comment by wtkns** [comment] 2020-03-29 03:35
not sure if this is what you need, but git submodule status returns

` 7b5d95400306232c1faef43620e703f7ae2b49e8 editors/sc-el (7b5d954)`

i ran git submodule update --recursive --remote and it returned:
 
```
Submodule path 'editors/sc-el': checked out '7bfbd1929d6e122ee609d7df006e57b351755c74'
Submodule path 'editors/scvim': checked out 'd80cf6e84ed4de3fa0cc1560bf3c1de5adad80fe'
Submodule path 'external_libraries/link': checked out '0b77cc2c15a4f62d185b5bf960c4f9e14b8f1ca6'
Submodule path 'external_libraries/link/modules/asio-standalone': checked out '8087252a0c3c2f0baad96ddbd6554db17a846376'
Submodule path 'external_libraries/nova-tt': checked out '55da93741e76632579b63004d3378139e32d634f'
Submodule path 'external_libraries/portaudio_sc_org': checked out '3822b3c30ec68bd514b5adfea2e8147cf52e0649'
Submodule path 'external_libraries/yaml-cpp': checked out 'b659858b19766e91e3e0cc9385419b287ac999cf'

i reset the git repo and deleted the build folder, reran cmake and make and got the same result. I know very little about this stuff, so let me know if i should try something else.

**Comment by wtkns** [comment] 2020-03-29 03:43
wait, sorry, do i need to check out the submodule branch manually?  or is the update sufficient?

**Comment by brianlheim** [comment] 2020-04-01 12:43
ignore what i said about master of sc-el. yes, i was asking you to check out master of that submodule but i see it's already updated to that.

just tried this locally on arch linux and could not reproduce. i am not an emacs user, but from a quick google search and a look at this repository's history, it seems that https://github.com/supercollider/scel/pull/18/files is probably related. can you try again checking out sc-el prior to that change? `cd editors/sc-el && git checkout b6e5d1b`. or experiment with changing the required packages/includes in `sclang-help.el`. you shouldn't need to delete/reset anything in between builds, just editing the files or checking out a different commit and running `make sclang-help.elc` should be fine.

**Comment by wtkns** [comment] 2020-04-01 20:11
after checking out that commit and running make sclang-help.elc it succeeded. there were a handful of warnings, which more or less added up to:

sclang-help.el:662:1:Warning: the following functions might not be defined at
    runtime: gensym, reduce, remove-if
sclang-help.el:662:1:Warning: the following functions are not known to be
    defined: w3m-edit-current-url, w3m-copy-buffer, w3m-find-file
Built target sclang-help.elc

after this i was able to build SC with SC_EL=ON

**Comment by brianlheim** [comment] 2020-04-01 22:22
thanks ! @mlang can you take a look at this if you have time?

**Closed** 2020-04-02 14:05 UTC
